version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  bot:
    build: ./bot
    environment:
      - TELEGRAM_API_TOKEN=<Токен бота>
    depends_on:
      - web

volumes:
  mongo_data:
